name: Dast Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]


jobs:
    DAST-testing-with-OWASP-ZAP:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
            with:
              ref: "main"
         
          - name: Set up Python
            uses: actions/setup-python@v3
            with:
              python-version: 3.11

          - name: Install dependencies
            run: |
              sudo pip install -r requirements.txt
              sudo python app.py &

          - name: ZAP Scan
            uses: zaproxy/action-full-scan@v0.7.0
            with:
             target: 'http://127.0.0.1:8501'
             artifact_name: 'DAST-results-zap_scan'
         
          - name : Exit ZAP
            run: exit 0
         
            env:
              GITHUB_TOKEN: ${{ secrets.CLA_WRITE_ACCESS }}
